name: ${project.name}
version: ${project.version}
description: ${project.description}
main: me.newt.multiplier.MultiplierPlugin
api-version: 1.16
authors: [Newt]
softdepend: [mcMMO, Jobs]
website: https://github.com/JustDJplease/ExperienceBooster

commands:
  multiplier:
    description: Root command for multipliers.
    aliases: [multipliers]

permissions:
  # Root for all commands
  multiplier.*:
    description: Root permission for all commands and features.
    children:
      multiplier.user.activate: true
      multiplier.user.thank: true
      multiplier.admin.give: true
      multiplier.admin.list: true
      multiplier.admin.reload: true
      multiplier.admin.remove: true
      multiplier.admin.start: true
      multiplier.admin.stop: true
  # Root for user commands
  multiplier.user.*:
    description: Root permission for all user commands.
    children:
      multiplier.user.activate: true
      multiplier.user.thank: true
  multiplier.user.activate:
    description: Permission for opening the GUI.
    default: true
  multiplier.user.thank:
    description: Permission to use the thank command.
    default: true
  # Root for admin commands
  multiplier.admin.*:
    description: Root permission for all admin commands.
    children:
      multiplier.admin.give: true
      multiplier.admin.list: true
      multiplier.admin.reload: true
      multiplier.admin.remove: true
      multiplier.admin.start: true
      multiplier.admin.stop: true
  multiplier.admin.give:
    description: Permission to use the give command.
    default: op
  multiplier.admin.list:
    description: Permission to use the list command.
    default: op
  multiplier.admin.reload:
    description: Permission to use the reload command.
    default: op
  multiplier.admin.remove:
    description: Permission to use the remove command.
    default: op
  multiplier.admin.start:
    description: Permission to use the start command.
    default: op
  multiplier.admin.stop:
    description: Permission to use the stop command.
    default: op