name: ${project.name}
version: ${project.version}
description: ${project.description}
main: me.newt.multiplier.MultiplierPlugin
api-version: 1.16
authors: [Newt]
softdepend: [mcMMO, Jobs]
website: https://github.com/JustDJplease/ExperienceBooster

commands:
  multiplier:
    description: Manage your multipliers and activate boosts.
    permission: multiplier.user

permissions:
  multiplier.*:
    description: Root permission for all commands and features.
    children:
      multiplier.user: true
      multipler.admin: true
  multiplier.user:
    description: Manage your multipliers and activate boosts.
    default: true
  multiplier.admin:
    description: Manage multipliers of others.
    default: op